//
// Created by paulo on 17-Nov-18.
//

#ifndef TRABALHO_1_CLION_INTERAPRACOMODACAO_H
#define TRABALHO_1_CLION_INTERAPRACOMODACAO_H


class InterAprAcomodacao {

};


#endif //TRABALHO_1_CLION_INTERAPRACOMODACAO_H
