//
// Created by paulo on 04-Sep-18.
//

#ifndef TRABALHO_1_CLION_CAPACIDADE_DE_ACOMODACAO_H
#define TRABALHO_1_CLION_CAPACIDADE_DE_ACOMODACAO_H


class Capacidade_De_Acomodacao {

};


#endif //TRABALHO_1_CLION_CAPACIDADE_DE_ACOMODACAO_H
