//
// Created by paulo on 17-Nov-18.
//

#ifndef TRABALHO_1_CLION_INTERSERVACOMODACAO_H
#define TRABALHO_1_CLION_INTERSERVACOMODACAO_H


class InterServAcomodacao {

};


#endif //TRABALHO_1_CLION_INTERSERVACOMODACAO_H
