//
// Created by paulo on 17-Nov-18.
//

#ifndef TRABALHO_1_CLION_INTERSERVAUTENTICACAO_H
#define TRABALHO_1_CLION_INTERSERVAUTENTICACAO_H


class InterServAutenticacao {

};


#endif //TRABALHO_1_CLION_INTERSERVAUTENTICACAO_H
