//
// Created by paulo on 16-Nov-18.
//

#ifndef TRABALHO_1_CLION_CNTRAPRAUTENTICACAO_H
#define TRABALHO_1_CLION_CNTRAPRAUTENTICACAO_H


class CntrAprAutenticacao {

};


#endif //TRABALHO_1_CLION_CNTRAPRAUTENTICACAO_H
