//
// Created by paulo on 16-Nov-18.
//

#ifndef TRABALHO_1_CLION_CNTRSSERVAUTENTICACAO_H
#define TRABALHO_1_CLION_CNTRSSERVAUTENTICACAO_H


class CntrsServAutenticacao {

};


#endif //TRABALHO_1_CLION_CNTRSSERVAUTENTICACAO_H
